### ISSUE TITLE
ENV questions 

### ISSUE THREAD

**Issue by blkluv** [dfstio/minanftio#3]
Do you have a direct contact link to ask questions about the ENV information?

**Comment by dfstio** [comment]
Thank you for your query regarding our ENV information. To better assist you with your questions, we suggest initially referring to the Netlify documentation available at: https://docs.netlify.com/environment-variables/overview/

You may also find it beneficial to join discussions on the Netlify forums, which can be accessed at: https://answers.netlify.com/. This platform fosters active engagement and exchange of knowledge among users, potentially offering solutions to your queries.

However, if you find your question unanswered or if it requires deeper technical support, please feel free to reach out to our premium support at support@minanft.io. In your message, kindly include a detailed description of your issue, the environment and tools you are using, as well as your KYC information. Once we receive this information, our team will evaluate the support hours needed and subsequently provide you with a quote for the premium support services.

We are here to ensure your experience with our platform is seamless and productive. Please don't hesitate to reach out if you have any further questions or concerns.
